### ISSUE TITLE
Double saving indication

### ISSUE THREAD

**Issue by FunkyPenguin24** [youugotssponged/SpongeQR#1]
Just generated two QR codes for a side project I'm working on, and didn't notice when I saved the second one that I hadn't hit generate again so both the QR codes were the same. I was just wondering if it could be made a bit more fool proof (I'm a bit of a fool) with a warning or something just to let users know that they are saving the same code twice. Other than that I love this app and how easy it is to use.

**Comment by youugotssponged** [comment]
I'll get right on it! Thank you for your feedback @FunkyPenguin24

**Comment by youugotssponged** [comment]
Hi @FunkyPenguin24 could you take a look at the latest release -> https://github.com/youugotssponged/SpongeQR/releases/tag/v1.0.4-release and let me know what you think? if you're happy i will close this issue.
